<a href="https://colab.research.google.com/github/rafaelrdealmeida/fundamentos_2026_lantri01/blob/main/notebooks/encontro_2026_lantri_01.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Introdução ao Pensamento computacional

## Ferramentas/Serviços utilizados

- Google Colab (notebook com codigo)
- Github (rede social de código)
- Git (programa de versionamento de código)


## Pilares
- Decomposição
- Abstração
- Identificação de padrões
- Lógica

## Noções Gerais

- Exemplos a partir de coleta de dados
  - Site MRE - Notas de imprensa
    - [x] Link do site: https://www.gov.br/mre/pt-br/canais_atendimento/imprensa/notas-a-imprensa/notas-a-imprensa
    - [x] Entender a estrutura da fonte de informação
    - [ ] Realizar a coleta
    - [ ] Inserir as informações em um banco de dados
    - [ ] Utilizar as informações (analise de dados)


### Padrão de paginação das notas de imprensa
  - https://www.gov.br/mre/pt-br/canais_atendimento/imprensa/notas-a-imprensa/notas-a-imprensa?b_start:int=0
   - https://www.gov.br/mre/pt-br/canais_atendimento/imprensa/notas-a-imprensa/notas-a-imprensa?b_start:int=30
   - Pagina final (10/02/2026): 6210

## Importação de bibliotecas/pogramas utilizados neste arquivo

In [1]:
!pip install tinydb

Collecting tinydb
  Downloading tinydb-4.8.2-py3-none-any.whl.metadata (6.7 kB)
Downloading tinydb-4.8.2-py3-none-any.whl (24 kB)
Installing collected packages: tinydb
Successfully installed tinydb-4.8.2

In [2]:
# programas/bibliotecas utilizados no script/codigo
import httpx # Responsável pelas requisições web
from bs4 import BeautifulSoup # Responsável por realizar o web scraping (coletar os dados)
from tinydb import TinyDB, Query

## Criação do banco json

In [3]:
def inserir_no_banco(dados, link_noticia):
  arquivo_banco_dados = "nota_mre.json"
  db = TinyDB(arquivo_banco_dados)


  # Evitar dados repetidos no banco
  Buscar = Query()
  verificar_link = db.contains(Buscar.link == link_noticia)

  if not verificar_link:
    print("Inserindo nova informação no banco")
    db.insert(dados)
  else:
    print("Link já existe no banco. Esta informação não será inserida novamente")

In [4]:
# Variável e tipos de dados (string, lista, numero)
paginas = ["https://www.gov.br/mre/pt-br/canais_atendimento/imprensa/notas-a-imprensa/notas-a-imprensa?b_start:int=0"]

def acessa_pagina (link):
  print (f"Estamos na pagina:{link}")

  # Define headers para a requisição, simulando um navegador
  headers = {
      'User-Agent': "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/110.0.0.0 Safari/537.36",
      'Accept-Language': 'en-US,en;q=0.9',
      'Accept-Encoding': 'gzip, deflate, br',
      'Connection': 'keep-alive',
  }

  timeout = httpx.Timeout(connect=20.0, read=30.0, write=20.0, pool=10.0)
  pag_web = httpx.get(link, headers=headers, timeout=timeout)
  bs = BeautifulSoup(pag_web, "html.parser")
  return bs

# loop for
# beautifulsoap >> find e find_all

for pagina in paginas:
  pagina_inteira = acessa_pagina(pagina)
  lista_noticias = pagina_inteira.find("div", attrs={"id": "content-core"}).find_all("article")
  for noticia in lista_noticias:
    # titulo
    try:
      titulo = noticia.find("h2", attrs={"class": "tileHeadline"}).text.strip()
      print(titulo)
    except:
        titulo = ""

    #link
    try:
      link_noticia = noticia.a["href"]
      print(link_noticia)
    except:
      link_noticia = ""
    # numero da nota - exemplo: NOTA À IMPRENSA Nº 72
    # numero da nota - exemplo: NOTA À IMPRENSA N° 590
    num_nota = noticia.find("span", attrs={"class": "subtitle"}).text.strip()
    # print(num_nota)
    # num_nota = noticia.find(attrs={"class": "subtitle"}).text.strip()
    num_nota = num_nota.replace("NOTA À IMPRENSA N°", "").replace("NOTA À IMPRENSA Nº", "").strip()
    print(num_nota)
    print("###")
    # data
    # horário
    data_hora = noticia.find_all("span",attrs={"class": "summary-view-icon"})
    data= data_hora[0].text.strip()
    hora = data_hora[1].text.strip()
    print(data)
    print(hora)
    conteudo = acessa_pagina (link_noticia)
    paragrafos = conteudo.find("div", attrs={"property":"rnews:articleBody"}).find_all("p")
    lista_paragrafos = []
    for paragrafo in paragrafos:
      lista_paragrafos.append(paragrafo.text.strip())
    print(lista_paragrafos)
    # função para inserir dados coletados no banco
    dados = {
        "titulo": titulo,
        "link": link_noticia,
        "data": data,
        "hora": hora,
        "num_nota": num_nota,
        "paragrafo": lista_paragrafos
    }
    inserir_no_banco(dados,link_noticia)

Estamos na pagina:https://www.gov.br/mre/pt-br/canais_atendimento/imprensa/notas-a-imprensa/notas-a-imprensa?b_start:int=0
Redução dos valores cobrados de passaportes emitidos no exterior
https://www.gov.br/mre/pt-br/canais_atendimento/imprensa/notas-a-imprensa/reducao-dos-valores-cobrados-de-passaportes-emitidos-no-exterior
154
###
04/05/2026
17h15
Estamos na pagina:https://www.gov.br/mre/pt-br/canais_atendimento/imprensa/notas-a-imprensa/reducao-dos-valores-cobrados-de-passaportes-emitidos-no-exterior
['A partir de 1º de junho de 2026, os valores cobrados em moeda estrangeira para a emissão de passaportes brasileiros nas embaixadas e consulados do Brasil no exterior serão reduzidos pela metade, aproximando-os dos valores cobrados no Brasil.', 'A medida, formalizada pela Portaria MRE nº 664/2026, visa a contribuir para a manutenção da documentação brasileira em dia por parte de indivíduos e famílias binacionais no exterior, em especial de crianças nascidas fora do Brasil.', 'O passaporte é documento essencial ao exercício de direitos fundamentais dos cidadãos brasileiros no exterior. Ao torná-lo mais acessível, a medida reforça o compromisso do governo brasileiro com o aprimoramento contínuo dos serviços consulares e com a atenção à comunidade brasileira no mundo.']
Inserindo nova informação no banco
IX Rodada Negociadora MERCOSUL-Canadá - Nota Conjunta MRE/MDIC/MAPA
https://www.gov.br/mre/pt-br/canais_atendimento/imprensa/notas-a-imprensa/ix-rodada-negociadora-mercosul-canada-nota-conjunta-mre-mdic-mapa-1
153
###
01/05/2026
19h00
Estamos na pagina:https://www.gov.br/mre/pt-br/canais_atendimento/imprensa/notas-a-imprensa/ix-rodada-negociadora-mercosul-canada-nota-conjunta-mre-mdic-mapa-1
['Realizou-se, entre os dias 27 e 30 de abril, em Brasília, a IX Rodada Negociadora do Acordo de Livre Comércio entre o MERCOSUL e o Canadá.', 'As negociações, retomadas em outubro passado, refletem o interesse das partes em aprofundar as relações econômicas e comerciais, promovendo maior integração produtiva entre as economias do MERCOSUL e do Canadá.', 'Foram realizadas reuniões presenciais dos grupos técnicos sobre comércio de bens, serviços e serviços financeiros, regras de origem, propriedade intelectual, barreiras sanitárias e fitossanitárias e comércio e desenvolvimento sustentável. Houve também reuniões híbridas sobre compras governamentais, barreiras técnicas ao comércio e comércio e trabalho.', 'Durante a rodada, três capítulos do Acordo encaminharam-se para o encerramento. Nova rodada será realizada em maio, para que os grupos avancem na conclusão da negociação.']
Inserindo nova informação no banco
Nota Conjunta Brasil-Espanha sobre sequestro em águas internacionais
https://www.gov.br/mre/pt-br/canais_atendimento/imprensa/notas-a-imprensa/nota-conjunta-brasil-espanha-sobre-sequestro-em-aguas-internacionais
152
###
01/05/2026
12h00
Estamos na pagina:https://www.gov.br/mre/pt-br/canais_atendimento/imprensa/notas-a-imprensa/nota-conjunta-brasil-espanha-sobre-sequestro-em-aguas-internacionais
['Os governos do Brasil e da Espanha condenam, nos termos mais enérgicos, o sequestro de dois de seus cidadãos em águas internacionais por parte do Governo de Israel.', 'Ambos encontravam-se em embarcações da flotilha Global Sumud, abordadas por forças israelenses na altura da Grécia, e não foram liberados quando da interceptação dessas naves, e posterior desembarque dos passageiros e tripulantes na ilha de Creta.', 'Esta ação flagrantemente ilegal das autoridades de Israel, fora de sua jurisdição, é uma afronta ao Direito Internacional, acionável em cortes internacionais, e configura delito em nossas respectivas jurisdições.', 'Os governos do Brasil e da Espanha exigem do governo de Israel o retorno imediato de seus cidadãos, com plenas garantias de segurança, e que se facilite o acesso consular imediato para sua assistência e proteção.']
Inserindo nova informação no banco
Declaração Conjunta sobre os Ataques Israelenses à Flotilha Global Sumud, 30 de abril de 2026
https://www.gov.br/mre/pt-br/canais_atendimento/imprensa/notas-a-imprensa/declaracao-conjunta-sobre-os-ataques-israelenses-a-flotilha-global-sumud-30-de-abril-de-2026-1
NOTA À IMPRENSA N. 151
###
30/04/2026
20h57
Estamos na pagina:https://www.gov.br/mre/pt-br/canais_atendimento/imprensa/notas-a-imprensa/declaracao-conjunta-sobre-os-ataques-israelenses-a-flotilha-global-sumud-30-de-abril-de-2026-1
['.', 'Declaração Conjunta dos Ministros das Relações Exteriores do Brasil, Turquia, Bangladesh, Colômbia, Jordânia, Líbia, Malásia, Maldivas, Mauritânia, Paquistão, África do Sul e Espanha sobre os Ataques Israelenses à Flotilha Global Sumud, 30 de abril de 2026', 'Os Ministros das Relações Exteriores da República Federativa do Brasil, da República da Turquia, do Reino Hachemita da Jordânia, da República Islâmica da Mauritânia, da República Islâmica do Paquistão, do Reino da Espanha, da Malásia, da República Popular de Bangladesh, da República da Colômbia, da República das Maldivas, da República da África do Sul e do Estado da Líbia condenam, nos termos mais enérgicos, o ataque israelense à Flotilha Global Sumud, uma iniciativa humanitária civil pacífica destinada a chamar a atenção da comunidade internacional para a catástrofe humanitária em Gaza.', 'Os ataques israelenses contra as embarcações e a detenção ilegal de ativistas humanitários em águas internacionais constituem flagrantes violações do direito internacional e do direito internacional humanitário.', 'Os Ministros manifestam profunda preocupação com a segurança dos ativistas civis e instam as autoridades israelenses a adotarem as medidas necessárias para assegurar sua libertação imediata.', 'Os Ministros também conclamam a comunidade internacional a cumprir suas obrigações morais e jurídicas de respeitar o direito internacional, proteger civis e assegurar a responsabilização por essas violações.', '***', 'Joint Statement by the Foreign Ministers of Türkiye, Bangladesh, Brazil, Colombia, Jordan, Libya, Malaysia, Maldives, Mauritania, Pakistan, South Africa, and Spain Regarding the Israeli Assaults on the Global Sumud Flotilla, 30 April 2026', "The Ministers of Foreign Affairs of the Republic of Türkiye, Federative Republic of Brazil, Hashemite Kingdom of Jordan, Islamic Republic of Mauritania, Islamic Republic of Pakistan, Kingdom of Spain, Malaysia, People's Republic of Bangladesh, Republic of Colombia, Republic of Maldives, Republic of South Africa, and State of Libya condemn in the strongest terms the Israeli assault on the Global Sumud Flotilla, a peaceful civilian humanitarian initiative aimed at drawing the attention of the international community to the humanitarian catastrophe in Gaza.", 'The Israeli attacks against the vessels and the unlawful detention of humanitarian activists in international waters constitute flagrant violations of international law and international humanitarian law.', 'The Ministers are deeply concerned about the safety of the civilian activists and urge the Israeli authorities to take the necessary measures to ensure their immediate release.', 'The Ministers also call on the international community to fulfill their moral and legal obligations to uphold international law, protect civilians, and ensure accountability for these violations.']
Inserindo nova informação no banco
Abertura de mercado para o Brasil no Chile - Nota Conjunta MRE/MAPA
https://www.gov.br/mre/pt-br/canais_atendimento/imprensa/notas-a-imprensa/abertura-de-mercado-para-o-brasil-no-chile-nota-conjunta-mre-mapa
150
###
29/04/2026
17h49
Estamos na pagina:https://www.gov.br/mre/pt-br/canais_atendimento/imprensa/notas-a-imprensa/abertura-de-mercado-para-o-brasil-no-chile-nota-conjunta-mre-mapa
['O governo brasileiro concluiu negociações que permitirão ao Brasil exportar grãos secos de destilaria (DDG/DDGS) para o Chile.', 'A abertura beneficia importante insumo agrícola gerado a partir da produção de etanol de milho. Os grãos secos de destilaria (DDG/DDGS) são utilizados na produção de ração para aves, bovinos e suínos.', 'Em 2025, o Brasil exportou mais de US$ 2,2 bilhões em produtos agropecuários para o Chile, com destaque para carnes, produtos florestais e o complexo soja.', 'Com esse anúncio, o agronegócio brasileiro alcança 601 aberturas de mercado desde 2023.', 'Tais resultados são fruto do trabalho conjunto entre o Ministério das Relações Exteriores (MRE) e o Ministério da Agricultura e Pecuária (MAPA).']
Inserindo nova informação no banco
Promulgação do Acordo Provisório de Comércio entre o MERCOSUL e a União Europeia – Nota Conjunta MRE/MDIC/MAPA
https://www.gov.br/mre/pt-br/canais_atendimento/imprensa/notas-a-imprensa/promulgacao-do-acordo-provisorio-de-comercio-entre-o-mercosul-e-a-uniao-europeia-2013-nota-conjunta-mre-mdic-mapa
149
###
28/04/2026
19h20
Estamos na pagina:https://www.gov.br/mre/pt-br/canais_atendimento/imprensa/notas-a-imprensa/promulgacao-do-acordo-provisorio-de-comercio-entre-o-mercosul-e-a-uniao-europeia-2013-nota-conjunta-mre-mdic-mapa
['O Presidente Luiz Inácio Lula da Silva assinou hoje (28/04) Decreto que incorpora o Acordo Provisório de Comércio entre o MERCOSUL e a União Europeia ao ordenamento jurídico brasileiro.\xa0Fruto de mais de 25 anos de negociações, o Acordo é um marco histórico para os dois blocos, que estabelecem, a partir do início de sua aplicação provisória, em 1º de maio, uma das maiores áreas de livre comércio do planeta, composta por 31 países, 720 milhões de pessoas e um PIB combinado que ultrapassa os US$ 22 trilhões.\xa0A ágil promulgação do Acordo MERCOSUL-UE reflete a prioridade dada ao tema pelo Presidente Lula desde o início de seu terceiro mandato. O Acordo beneficiará toda a sociedade brasileira, ao contribuir para a expansão das nossas parcerias globais, o aumento e a diversificação das nossas exportações, a redução de custos para produtores e consumidores e a geração de renda e de novas oportunidades para trabalhadores e empresas.Acesse aqui o factsheet sobre o Acordo.']
Inserindo nova informação no banco
Mortes de brasileiros no Líbano em decorrência de ataques israelenses
https://www.gov.br/mre/pt-br/canais_atendimento/imprensa/notas-a-imprensa/mortes-de-brasileiros-no-libano-em-decorrencia-de-ataques-israelenses
148
###
27/04/2026
19h04
Estamos na pagina:https://www.gov.br/mre/pt-br/canais_atendimento/imprensa/notas-a-imprensa/mortes-de-brasileiros-no-libano-em-decorrencia-de-ataques-israelenses
['O governo brasileiro tomou conhecimento, com consternação e pesar, das mortes, em 26/4, de criança brasileira, de 11 anos, de sua mãe, também brasileira, e de seu pai libanês, vítimas de ataque das Forças de Defesa de Israel. Outro filho do casal, igualmente brasileiro, encontra-se hospitalizado. A família encontrava-se em sua residência, no distrito de Bint Jbeil, no Sul do Líbano, no momento do bombardeio.', 'Esse ataque constitui mais um exemplo das reiteradas e inaceitáveis violações ao cessar-fogo anunciado em 16 de abril, as quais já resultaram na morte de dezenas de civis libaneses, incluindo mulheres e crianças, assim como de uma jornalista e de dois integrantes franceses da Força Interina das Nações Unidas no Líbano (UNIFIL).', 'Ao expressar sinceras condolências aos familiares das vítimas, o Brasil reitera sua mais veemente condenação a todos os ataques perpetrados durante a vigência do cessar-fogo, tanto por parte das forças israelenses quanto do Hezbollah. Condena, ainda, as demolições sistemáticas de residências e de outras estruturas civis no sul do Líbano, levadas a efeito, ao longo das últimas semanas, pelas forças israelenses, e a persistência do deslocamento forçado de mais de um milhão de libaneses.', 'Nesse contexto, o Brasil exorta as partes ao cumprimento integral dos termos da Resolução 1701 (2006) do Conselho de Segurança das Nações Unidas, que estabeleceu os termos do cessar-fogo que encerrou a guerra de 2006, e à imediata cessação das hostilidades, com a retirada completa das forças israelenses do território libanês.', 'A Embaixada do Brasil em Beirute está em contato com a família dos brasileiros falecidos para prestar assistência consular, incluindo para o filho hospitalizado.']
Inserindo nova informação no banco
Ataques terroristas no Mali
https://www.gov.br/mre/pt-br/canais_atendimento/imprensa/notas-a-imprensa/ataques-terroristas-no-mali
147
###
27/04/2026
13h38
Estamos na pagina:https://www.gov.br/mre/pt-br/canais_atendimento/imprensa/notas-a-imprensa/ataques-terroristas-no-mali
['O Governo brasileiro manifesta grave preocupação com os ataques terroristas ocorridos no último fim de semana em seis cidades do Mali, incluindo a capital Bamako, que vitimaram um número ainda impreciso de civis e militares, entre os quais o ministro da Defesa daquele país, General Sadio Camara.Ao manifestar sinceras condolências às famílias das vítimas e o desejo de pronta recuperação aos feridos, o Brasil reitera o firme repúdio a todo ato de terrorismo, sob qualquer pretexto.Não se tem notícia de cidadãos brasileiros entre as vítimas dos ataques. O plantão consular da embaixada do Brasil em Bamako é +223 74 74 95 24.']
Inserindo nova informação no banco
Atentado na Colômbia
https://www.gov.br/mre/pt-br/canais_atendimento/imprensa/notas-a-imprensa/atentado-na-colombia-1
146
###
27/04/2026
08h45
Estamos na pagina:https://www.gov.br/mre/pt-br/canais_atendimento/imprensa/notas-a-imprensa/atentado-na-colombia-1
['O governo brasileiro condena o ataque perpetrado no Departamento de Cauca, na Colômbia, em 25 de abril, que deixou mais de uma dezena de mortos e vários feridos.O governo brasileiro manifesta sua solidariedade às famílias das vítimas e ao povo e governo colombianos.O Brasil reafirma, ainda, o seu apoio ao\xa0 "Compromisso com um processo eleitoral livre e em paz na Colombia", iniciativa da Defensoria do Povo da Colômbia endossada pelo Escritório do Alto Comissário das Nações Unidas na Colômbia para Direitos Humanos, pela Missão de Apoio ao Processo de Paz na Colômbia da Organização dos Estados Americanos (MAPP-OEA), pela Missão de Verificação das Nações Unidas na Colômbia (UNVMC), pela Conferência Episcopal colombiana e por outras missões diplomáticas em Bogotá.Não há registro de nacionais brasileiros entre as vítimas do atentado.']
Inserindo nova informação no banco
Apresentação da candidatura do Professor George Rodrigo Bandeira Galindo ao Tribunal Internacional do Direito do Mar
https://www.gov.br/mre/pt-br/canais_atendimento/imprensa/notas-a-imprensa/apresentacao-da-candidatura-do-professor-george-rodrigo-bandeira-galindo-ao-tribunal-internacional-do-direito-do-mar
145
###
24/04/2026
15h57
Estamos na pagina:https://www.gov.br/mre/pt-br/canais_atendimento/imprensa/notas-a-imprensa/apresentacao-da-candidatura-do-professor-george-rodrigo-bandeira-galindo-ao-tribunal-internacional-do-direito-do-mar
['Realizou-se, em 23 de abril, coquetel de apresentação da candidatura do Professor George Rodrigo Bandeira Galindo ao Tribunal Internacional do Direito do Mar (TIDM), para o mandato 2026-2035. O evento contou com a participação do Ministro das Relações Exteriores, Mauro Vieira, e do Presidente do Superior Tribunal de Justiça, Ministro Herman Benjamin.', 'Com sede em Hamburgo, na Alemanha, o TIDM, foi estabelecido pela Convenção das Nações Unidas para o Direito do Mar (CNUDM). Possui jurisdição sobre qualquer disputa relacionada à interpretação e à aplicação da CNUDM, bem como sobre todo e qualquer caso em que exista acordo que reconheça a jurisdição do Tribunal, como o Acordo de Pesca de Nova York. Além dos Estados e Organizações Internacionais que são Partes da CNUDM, o Tribunal também é aberto a Estados ou organizações internacionais que não aderiram à Convenção.', 'Na ocasião, os representantes das Embaixadas dos Estados Partes do TIDM acreditados em Brasília puderam conhecer melhor a plataforma de atuação proposta pelo candidato brasileiro, pautada por enfoque imparcial, independente e técnico, com vistas à preservação e ao aprimoramento da institucionalidade da CNUDM.']
Inserindo nova informação no banco
Aberturas de mercado para o Brasil em Cuba, nas Filipinas e na Coreia do Sul
https://www.gov.br/mre/pt-br/canais_atendimento/imprensa/notas-a-imprensa/aberturas-de-mercado-para-o-brasil-em-cuba-nas-filipinas-e-na-coreia-do-sul
144
###
24/04/2026
15h48
Estamos na pagina:https://www.gov.br/mre/pt-br/canais_atendimento/imprensa/notas-a-imprensa/aberturas-de-mercado-para-o-brasil-em-cuba-nas-filipinas-e-na-coreia-do-sul
['O governo brasileiro concluiu negociações que permitirão a exportação de diversos produtos para Cuba, Filipinas e Coreia do Sul.', 'Em Cuba, foi autorizada a exportação de carne bovina e suína com osso. Em 2025, o Brasil exportou mais de US$ 255 milhões em produtos do agronegócio para o país.', 'Nas Filipinas, país para o qual o Brasil exportou cerca de US$ 1,8 bilhão em produtos agropecuários no ano passado, as autoridades locais aprovaram a exportação de carne bovina resfriada com e sem osso.', 'Na Coreia do Sul, obteve-se abertura de mercado para exportação de castanha-do-brasil com e sem casca, de castanha de baru e de castanha de caju. Extraídos de forma sustentável, esses produtos beneficiarão economicamente as comunidades envolvidas em suas cadeias produtivas. Em 2025, o Brasil exportou mais de US$ 2,4 bilhões em produtos agropecuários para o país.', 'Com estes anúncios, o agronegócio brasileiro alcança 600 aberturas de mercado desde o início de 2023.', 'Tais resultados são fruto do trabalho conjunto entre o Ministério das Relações Exteriores (MRE) e o Ministério da Agricultura e Pecuária (MAPA).']
Inserindo nova informação no banco
Aberturas de mercado para o Brasil no Togo - Nota Conjunta MRE/MAPA
https://www.gov.br/mre/pt-br/canais_atendimento/imprensa/notas-a-imprensa/aberturas-de-mercado-para-o-brasil-no-togo-nota-conjunta-mre-mapa
143
###
22/04/2026
19h20
Estamos na pagina:https://www.gov.br/mre/pt-br/canais_atendimento/imprensa/notas-a-imprensa/aberturas-de-mercado-para-o-brasil-no-togo-nota-conjunta-mre-mapa
['O governo brasileiro concluiu negociações que permitirão a exportação de material genético bovino (sêmen e embriões) para o Togo.As aberturas criam oportunidades para produtores brasileiros, bem como para a prestação de serviços de consultoria e assistência técnica. Em 2025, o Brasil exportou mais de US$ 148 milhões em produtos agropecuários para o Togo, com destaque para produtos do complexo sucroalcooleiro, carnes e couro.Com esse anúncio, o agronegócio brasileiro alcança 594 aberturas de mercado desde o início de 2023.Tais resultados são fruto do trabalho conjunto entre o Ministério das Relações Exteriores (MRE) e o Ministério da Agricultura e Pecuária (MAPA).']
Inserindo nova informação no banco
Atos adotados por ocasião da Visita de Estado do Presidente Luiz Inácio Lula da Silva a Hannover - Alemanha, 19 e 20 de abril de 2026
https://www.gov.br/mre/pt-br/canais_atendimento/imprensa/notas-a-imprensa/atos-adotados-por-ocasiao-da-visita-de-estado-do-presidente-luiz-inacio-lula-da-silva-a-hannover-alemanha-19-e-20-de-abril-de-2026-2
142
###
20/04/2026
13h13
Estamos na pagina:https://www.gov.br/mre/pt-br/canais_atendimento/imprensa/notas-a-imprensa/atos-adotados-por-ocasiao-da-visita-de-estado-do-presidente-luiz-inacio-lula-da-silva-a-hannover-alemanha-19-e-20-de-abril-de-2026-2
['Foram adotados\xa0os seguintes atos por ocasião\xa0da visita do Presidente\xa0Luiz Inácio Lula da Silva a Hannover - Alemanha, em 19 e 20 de abril de 2026:']
Inserindo nova informação no banco
Declaração Conjunta Brasil-Alemanha sobre apoio ao Fundo Florestas Tropicais para Sempre (TFFF) - Hannover, 20 de abril de 2026
https://www.gov.br/mre/pt-br/canais_atendimento/imprensa/notas-a-imprensa/declaracao-conjunta-brasil-alemanha-sobre-apoio-ao-fundo-florestas-tropicais-para-sempre-tfff-hannover-20-de-abril-de-2026-1
141
###
20/04/2026
11h12

# Transformar banco json e dataframe

- pre-analise - entendimento geral sobre o dataframe

In [5]:
import pandas as pd
import json

## Abrindo o rquivo json
with open("nota_mre.json") as f:
  raw = json.load(f)

df = pd.DataFrame.from_dict(raw["_default"], orient="index")

df

,titulo,link,data,hora,num_nota,paragrafo
1,Redução dos valores cobrados de passaportes em...,https://www.gov.br/mre/pt-br/canais_atendiment...,04/05/2026,17h15,154,"[A partir de 1º de junho de 2026, os valores c..."
2,IX Rodada Negociadora MERCOSUL-Canadá - Nota C...,https://www.gov.br/mre/pt-br/canais_atendiment...,01/05/2026,19h00,153,"[Realizou-se, entre os dias 27 e 30 de abril, ..."
3,Nota Conjunta Brasil-Espanha sobre sequestro e...,https://www.gov.br/mre/pt-br/canais_atendiment...,01/05/2026,12h00,152,"[Os governos do Brasil e da Espanha condenam, ..."
4,Declaração Conjunta sobre os Ataques Israelens...,https://www.gov.br/mre/pt-br/canais_atendiment...,30/04/2026,20h57,NOTA À IMPRENSA N. 151,"[., Declaração Conjunta dos Ministros das Rela..."
5,Abertura de mercado para o Brasil no Chile - N...,https://www.gov.br/mre/pt-br/canais_atendiment...,29/04/2026,17h49,150,[O governo brasileiro concluiu negociações que...
6,Promulgação do Acordo Provisório de Comércio e...,https://www.gov.br/mre/pt-br/canais_atendiment...,28/04/2026,19h20,149,[O Presidente Luiz Inácio Lula da Silva assino...
7,Mortes de brasileiros no Líbano em decorrência...,https://www.gov.br/mre/pt-br/canais_atendiment...,27/04/2026,19h04,148,"[O governo brasileiro tomou conhecimento, com ..."
8,Ataques terroristas no Mali,https://www.gov.br/mre/pt-br/canais_atendiment...,27/04/2026,13h38,147,[O Governo brasileiro manifesta grave preocupa...
9,Atentado na Colômbia,https://www.gov.br/mre/pt-br/canais_atendiment...,27/04/2026,08h45,146,[O governo brasileiro condena o ataque perpetr...
10,Apresentação da candidatura do Professor Georg...,https://www.gov.br/mre/pt-br/canais_atendiment...,24/04/2026,15h57,145,"[Realizou-se, em 23 de abril, coquetel de apre..."
11,"Aberturas de mercado para o Brasil em Cuba, na...",https://www.gov.br/mre/pt-br/canais_atendiment...,24/04/2026,15h48,144,[O governo brasileiro concluiu negociações que...
12,Aberturas de mercado para o Brasil no Togo - N...,https://www.gov.br/mre/pt-br/canais_atendiment...,22/04/2026,19h20,143,[O governo brasileiro concluiu negociações que...
13,Atos adotados por ocasião da Visita de Estado ...,https://www.gov.br/mre/pt-br/canais_atendiment...,20/04/2026,13h13,142,[Foram adotados os seguintes atos por ocasião ...
14,Declaração Conjunta Brasil-Alemanha sobre apoi...,https://www.gov.br/mre/pt-br/canais_atendiment...,20/04/2026,11h12,141,[No contexto da reunião bilateral entre o Pres...
15,III Consultas Intergovernamentais de Alto Níve...,https://www.gov.br/mre/pt-br/canais_atendiment...,20/04/2026,10h26,140,[1. Sob a presidência do Chanceler Federal Fri...
16,4ª Reunião de Alto Nível do Fórum Democracia S...,https://www.gov.br/mre/pt-br/canais_atendiment...,19/04/2026,07h58,139,"[Nosotras y nosotros, los Jefes de Estado y de..."
17,Declaração Conjunta Sobre a Situação em Cuba,https://www.gov.br/mre/pt-br/canais_atendiment...,18/04/2026,16h44,138,[À luz da evolução da situação em Cuba e das c...
18,Visita Oficial do Senhor Presidente da Repúbli...,https://www.gov.br/mre/pt-br/canais_atendiment...,18/04/2026,11h33,137,[O senhor Presidente da República realizará vi...
19,Cessar-fogo no Líbano,https://www.gov.br/mre/pt-br/canais_atendiment...,17/04/2026,15h23,136,[O governo brasileiro saúda o anúncio de cessa...
20,Abertura de mercado para o Brasil no Vietnã - ...,https://www.gov.br/mre/pt-br/canais_atendiment...,17/04/2026,12h31,135,[O governo brasileiro concluiu negociações com...
21,Atos adotados por ocasião da Visita de Estado ...,https://www.gov.br/mre/pt-br/canais_atendiment...,17/04/2026,11h27,134,"[Foram adotados os seguintes atos, por ocasião..."
22,Declaração Conjunta por ocasião da I Cúpula Es...,https://www.gov.br/mre/pt-br/canais_atendiment...,17/04/2026,11h02,133,"[., I CÚPULA ESPANHA-BRASIL, Declaração conjun..."
23,Ataques a Tiros em Escolas na Turquia,https://www.gov.br/mre/pt-br/canais_atendiment...,16/04/2026,17h56,132,"[O Governo brasileiro tomou conhecimento, com ..."
24,Visita oficial do senhor Presidente da Repúbli...,https://www.gov.br/mre/pt-br/canais_atendiment...,16/04/2026,11h51,131,"[Nos dias 19 e 20 de abril, o senhor President..."
25,Visita oficial do senhor Presidente da Repúbli...,https://www.gov.br/mre/pt-br/canais_atendiment...,15/04/2026,21h20,130,"[Realizar-se-á em Barcelona, em 17 de abril co..."
26,Aberturas de mercado para o Brasil na Arábia S...,https://www.gov.br/mre/pt-br/canais_atendiment...,15/04/2026,18h30,129,[O governo brasileiro concluiu negociações que...
27,Concessão de agrément ao Embaixador designado ...,https://www.gov.br/mre/pt-br/canais_atendiment...,15/04/2026,12h31,128,"[O governo brasileiro informa, com satisfação,..."
28,Chuvas em Angola,https://www.gov.br/mre/pt-br/canais_atendiment...,14/04/2026,21h24,127,"[O governo brasileiro tomou conhecimento, com ..."
29,"Aberturas de mercado para o Brasil no Vietnã, ...",https://www.gov.br/mre/pt-br/canais_atendiment...,14/04/2026,20h10,126,[O governo brasileiro concluiu negociações que...
30,Acidente em ponto turístico no Haiti,https://www.gov.br/mre/pt-br/canais_atendiment...,12/04/2026,21h40,125,"[O governo brasileiro tomou conhecimento, com ..."

In [6]:
# saber quantidade de linhas e colunas do dataframe
df.shape

(30, 6)

In [7]:
# saber colunas disponiveis
df.columns

Index(['titulo', 'link', 'data', 'hora', 'num_nota', 'paragrafo'], dtype='object')

In [8]:
# selecionar uma coluna em especifico
df["titulo"]

1     Redução dos valores cobrados de passaportes em...
2     IX Rodada Negociadora MERCOSUL-Canadá - Nota C...
3     Nota Conjunta Brasil-Espanha sobre sequestro e...
4     Declaração Conjunta sobre os Ataques Israelens...
5     Abertura de mercado para o Brasil no Chile - N...
6     Promulgação do Acordo Provisório de Comércio e...
7     Mortes de brasileiros no Líbano em decorrência...
8                           Ataques terroristas no Mali
9                                  Atentado na Colômbia
10    Apresentação da candidatura do Professor Georg...
11    Aberturas de mercado para o Brasil em Cuba, na...
12    Aberturas de mercado para o Brasil no Togo - N...
13    Atos adotados por ocasião da Visita de Estado ...
14    Declaração Conjunta Brasil-Alemanha sobre apoi...
15    III Consultas Intergovernamentais de Alto Níve...
16    4ª Reunião de Alto Nível do Fórum Democracia S...
17         Declaração Conjunta Sobre a Situação em Cuba
18    Visita Oficial do Senhor Presidente da Repúbli...
19                                Cessar-fogo no Líbano
20    Abertura de mercado para o Brasil no Vietnã - ...
21    Atos adotados por ocasião da Visita de Estado ...
22    Declaração Conjunta por ocasião da I Cúpula Es...
23                Ataques a Tiros em Escolas na Turquia
24    Visita oficial do senhor Presidente da Repúbli...
25    Visita oficial do senhor Presidente da Repúbli...
26    Aberturas de mercado para o Brasil na Arábia S...
27    Concessão de agrément ao Embaixador designado ...
28                                     Chuvas em Angola
29    Aberturas de mercado para o Brasil no Vietnã, ...
30                 Acidente em ponto turístico no Haiti
Name: titulo, dtype: object

In [9]:

# delimitar colunas do dataframe
df_delimitado = df[["titulo", "data"]]
df_delimitado

                                               titulo        data
1   Redução dos valores cobrados de passaportes em...  04/05/2026
2   IX Rodada Negociadora MERCOSUL-Canadá - Nota C...  01/05/2026
3   Nota Conjunta Brasil-Espanha sobre sequestro e...  01/05/2026
4   Declaração Conjunta sobre os Ataques Israelens...  30/04/2026
5   Abertura de mercado para o Brasil no Chile - N...  29/04/2026
6   Promulgação do Acordo Provisório de Comércio e...  28/04/2026
7   Mortes de brasileiros no Líbano em decorrência...  27/04/2026
8                         Ataques terroristas no Mali  27/04/2026
9                                Atentado na Colômbia  27/04/2026
10  Apresentação da candidatura do Professor Georg...  24/04/2026
11  Aberturas de mercado para o Brasil em Cuba, na...  24/04/2026
12  Aberturas de mercado para o Brasil no Togo - N...  22/04/2026
13  Atos adotados por ocasião da Visita de Estado ...  20/04/2026
14  Declaração Conjunta Brasil-Alemanha sobre apoi...  20/04/2026
15  III Consultas Intergovernamentais de Alto Níve...  20/04/2026
16  4ª Reunião de Alto Nível do Fórum Democracia S...  19/04/2026
17       Declaração Conjunta Sobre a Situação em Cuba  18/04/2026
18  Visita Oficial do Senhor Presidente da Repúbli...  18/04/2026
19                              Cessar-fogo no Líbano  17/04/2026
20  Abertura de mercado para o Brasil no Vietnã - ...  17/04/2026
21  Atos adotados por ocasião da Visita de Estado ...  17/04/2026
22  Declaração Conjunta por ocasião da I Cúpula Es...  17/04/2026
23              Ataques a Tiros em Escolas na Turquia  16/04/2026
24  Visita oficial do senhor Presidente da Repúbli...  16/04/2026
25  Visita oficial do senhor Presidente da Repúbli...  15/04/2026
26  Aberturas de mercado para o Brasil na Arábia S...  15/04/2026
27  Concessão de agrément ao Embaixador designado ...  15/04/2026
28                                   Chuvas em Angola  14/04/2026
29  Aberturas de mercado para o Brasil no Vietnã, ...  14/04/2026
30               Acidente em ponto turístico no Haiti  12/04/2026

In [10]:

# primeiras (head), ultimas (tail) e linhas aleatórias (sample)
df.head(10)

,titulo,link,data,hora,num_nota,paragrafo
1,Redução dos valores cobrados de passaportes em...,https://www.gov.br/mre/pt-br/canais_atendiment...,04/05/2026,17h15,154,"[A partir de 1º de junho de 2026, os valores c..."
2,IX Rodada Negociadora MERCOSUL-Canadá - Nota C...,https://www.gov.br/mre/pt-br/canais_atendiment...,01/05/2026,19h00,153,"[Realizou-se, entre os dias 27 e 30 de abril, ..."
3,Nota Conjunta Brasil-Espanha sobre sequestro e...,https://www.gov.br/mre/pt-br/canais_atendiment...,01/05/2026,12h00,152,"[Os governos do Brasil e da Espanha condenam, ..."
4,Declaração Conjunta sobre os Ataques Israelens...,https://www.gov.br/mre/pt-br/canais_atendiment...,30/04/2026,20h57,NOTA À IMPRENSA N. 151,"[., Declaração Conjunta dos Ministros das Rela..."
5,Abertura de mercado para o Brasil no Chile - N...,https://www.gov.br/mre/pt-br/canais_atendiment...,29/04/2026,17h49,150,[O governo brasileiro concluiu negociações que...
6,Promulgação do Acordo Provisório de Comércio e...,https://www.gov.br/mre/pt-br/canais_atendiment...,28/04/2026,19h20,149,[O Presidente Luiz Inácio Lula da Silva assino...
7,Mortes de brasileiros no Líbano em decorrência...,https://www.gov.br/mre/pt-br/canais_atendiment...,27/04/2026,19h04,148,"[O governo brasileiro tomou conhecimento, com ..."
8,Ataques terroristas no Mali,https://www.gov.br/mre/pt-br/canais_atendiment...,27/04/2026,13h38,147,[O Governo brasileiro manifesta grave preocupa...
9,Atentado na Colômbia,https://www.gov.br/mre/pt-br/canais_atendiment...,27/04/2026,08h45,146,[O governo brasileiro condena o ataque perpetr...
10,Apresentação da candidatura do Professor Georg...,https://www.gov.br/mre/pt-br/canais_atendiment...,24/04/2026,15h57,145,"[Realizou-se, em 23 de abril, coquetel de apre..."

In [11]:
df.describe(include="all")

,titulo,link,data,hora,num_nota,paragrafo
count,30,30,30,30,30,30
unique,30,30,16,28,30,30
top,Redução dos valores cobrados de passaportes em...,https://www.gov.br/mre/pt-br/canais_atendiment...,17/04/2026,19h20,154,"[A partir de 1º de junho de 2026, os valores c..."
freq,1,1,4,2,1,1

In [12]:
df.isnull().sum()

titulo       0
link         0
data         0
hora         0
num_nota     0
paragrafo    0
dtype: int64

In [13]:
# verificar linhas duplicadas
df.duplicated().sum()

TypeError: unhashable type: 'list'

### Tratamento de Dados e Visualização

Agora que entendemos a estrutura, vamos preparar os dados para extrair insights visuais. Um passo comum é converter colunas de texto em formatos que o computador entenda como 'tempo' (datetime) e criar gráficos.

In [ ]:
# 1. Converter a coluna de data para o formato datetime do Pandas
df['data_dt'] = pd.to_datetime(df['data'], dayfirst=True)

# 2. Contar quantas notícias temos por dia
noticias_por_dia = df['data_dt'].value_counts().sort_index()

display(noticias_por_dia)

#### Visualizando o Volume de Publicações

Vamos usar a biblioteca `matplotlib` (que já vem no ambiente) para criar um gráfico de barras simples.

In [ ]:
import matplotlib.pyplot as plt

# Criando o gráfico
plt.figure(figsize=(10, 5))
noticias_por_dia.plot(kind='bar', color='skyblue')

# Adicionando títulos e rótulos
plt.title('Quantidade de Notas à Imprensa por Data')
plt.xlabel('Data da Publicação')
plt.ylabel('Número de Notas')
plt.xticks(rotation=45)
plt.grid(axis='y', linestyle='--', alpha=0.7)

plt.show()

#### Analisando Palavras-Chave nos Títulos

Uma técnica simples de análise de texto para iniciantes é verificar a frequência de certas palavras-chave (como nomes de países).

In [ ]:
paises = ['Alemanha', 'Líbano', 'Vietnã', 'Togo', 'Haiti']
frequencia = {}

for pais in paises:
    # Conta em quantos títulos a palavra aparece
    frequencia[pais] = df['titulo'].str.contains(pais, case=False).sum()

# Converter para série para facilitar a plotagem
ser_freq = pd.Series(frequencia)

plt.figure(figsize=(8, 4))
ser_freq.sort_values(ascending=False).plot(kind='barh', color='lightgreen')
plt.title('Menções de Países nos Títulos das Notas')
plt.xlabel('Número de Menções')
plt.show()